language: ruby
rvm: 2.2
cache: bundler
script: make docs && find _site -type f -name *.html -exec ./.error-linkchecker {} \;
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local_dir: _site
  name: bot50
  email: bot@cs50.harvard.edu
  fqdn: docs.cs50.net
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
