asciidoc:
  ext: adoc
asciidoctor:
  attributes:
  - data-uri
  - icons=font
  - idprefix=
  - imagesdir=.
  - linkcss
  - pygments-css=class
  - sectlinks
  - showtitle
  - source-highlighter=pygments
  - stylesdir=css
  base_dir: :docdir
  safe: 0
destination: docs
exclude:
- Dockerfile 
- Makefile
- README.md 
gems:
- jekyll-asciidoc
