asciidoc:
  ext: adoc
asciidoctor:
  attributes:
  - data-uri
  - idprefix=
  - imagesdir=.
  - linkcss
  - pygments-css=class
  - sectlinks
  - showtitle
  - source-highlighter=pygments
  - stylesdir=css
  - toc=left
  - toclevels=4
collections:
  pages:
    output: true
    permalink: /:path
destination: docs
exclude:
- Dockerfile 
- Makefile
gems:
- jekyll-asciidoc
layouts_dir: _layouts
